<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTPC0K7AG1" failures="2" tests="8" name="ParameterTest" time="0.108" errors="0" timestamp="03 Oct 2019 15:03:47 GMT">
  <testcase classname="TestNg.RetryLogic" name="Test1" time="0.027">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestNg.RetryLogic" name="Test1" time="0.005">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestNg.RetryLogic" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestNg.RetryLogic" name="Test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestNg.RetryLogic.Test1(RetryLogic.java:10)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="TestNg.RetryLogic" name="Test2" time="0.0">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestNg.RetryLogic" name="Test2" time="0.005">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestNg.RetryLogic" name="Test2" time="0.005">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestNg.RetryLogic" name="Test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestNg.RetryLogic.Test2(RetryLogic.java:14)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- ParameterTest -->
